image: alpine:3.11

variables:
    COVERAGE_REPORT: coverage.xml

stages:
    - test
    - package

Test:
    image: "python:2.7"
    stage: test
    script:
        - pip install -r requirements.txt
        - coverage run -m unittest recent_projects_test
        - coverage report -m
        - coverage xml -o $COVERAGE_REPORT
    artifacts:
        reports:
            cobertura: $COVERAGE_REPORT
    coverage: '/TOTAL.*\s+(\d+%)$/'

Package:
    stage: package
    artifacts:
        paths:
            - "*.alfredworkflow"
    script:
        - apk add make zip
        - make
    only:
        - master
